Fixes issue #23
AkshayaKulasekaran/Basic-Programs-Python pull request #24
Opened 2021-05-23 09:33 UTC by imkritigupta

This PR fixes the issue by replacing the screenshots with the following code-

```
<img src="https://user-images.githubusercontent.com/82928579/119253135-69a45800-bbcd-11eb-824a-f08b1e549024.PNG" alt="issues & PRs" width=50%>
<img src="https://user-images.githubusercontent.com/82928579/119253194-bb4ce280-bbcd-11eb-8db2-8ca5abd18c23.PNG" alt="open issues" width=70%>
```
![newcapture1](https://user-images.githubusercontent.com/82928579/119255145-ac6b2d80-bbd7-11eb-9914-16566721af5c.PNG)
![newcapture2](https://user-images.githubusercontent.com/82928579/119255147-ae34f100-bbd7-11eb-8db2-59afe85bd6ab.PNG)

also, changed the sample code template with-

```
<img src="https://user-images.githubusercontent.com/82928579/119253831-af165480-bbd0-11eb-86ee-f359da5ea9c2.png" alt="sample code" width=50%>
```
![newcapture3](https://user-images.githubusercontent.com/82928579/119255123-93fb1300-bbd7-11eb-8f57-2e76c7287849.png)

2021-05-23 18:13 UTC, Akshu-on-github requested changes
Thanks for contributing - the screenshots look so much nicer!
Just that one thing about the alt text - I hope you don't mind!

2021-05-23 18:13 UTC, Akshu-on-github commented on CONTRIBUTING.md
> +<img src="https://user-images.githubusercontent.com/82928579/119253831-af165480-bbd0-11eb-86ee-f359da5ea9c2.png" alt="sample code" width=50%>
Please give verbal directions to identify the emphasized elements
For example,
```html
<!-- For the Issue and PR tabs-->
<img src="..." alt="Click the tabs next to the 'Code' tab (found below the name of the repository)">
```

2021-05-23 20:23 UTC, imkritigupta commented
Apologies! the following changes have been made as per the instructions, kindly have a look.
- Line 13 & 23 respectively:

```
<img src="https://user-images.githubusercontent.com/82928579/119253135-69a45800-bbcd-11eb-824a-f08b1e549024.PNG" alt="Click the tab 'Issues' or 'Pull requests' next to the 'code' tab (below the name of the repository)" width=50%> 
<img src="https://user-images.githubusercontent.com/82928579/119253831-af165480-bbd0-11eb-86ee-f359da5ea9c2.png" alt="Use the sample code template- click on 'Get started' (green button)" width=50%>
```

2021-05-25 19:29 UTC, merged

2021-05-25 19:29 UTC, Akshu-on-github commented
Thanks a million @imkritigupta! And congrats on your successful contribution!