Add the fortune-teller game
AkshayaKulasekaran/Basic-Programs-Python pull request #41
Opened 2021-08-07 18:28 UTC by Janhavi-2001

**This PR is related to**:  A simple Python code implementing a fortune-telling game via the generation of a random number.

2021-08-10 19:53 UTC, pokacyb commented
Hello!
It's my first pull request but I can try working on it if that's ok :)

2021-08-15 02:56 UTC, Akshu-on-github commented on Programs/fortune_teller.py
> +    if(choice == 'Y' or choice == 'y'):
Could you use this instead?
```py
if (choice.lower() == 'y'):
    # code block
```

2021-08-15 02:56 UTC, Akshu-on-github commented on Programs/fortune_teller.py
> +    elif(choice == 'N' or choice == 'n'):
Here too?

2021-08-15 02:57 UTC, Akshu-on-github requested changes
Thanks for contributing! Lemme know if you're up for making these changes @Janhavi-2001

2021-08-15 02:58 UTC, Akshu-on-github commented
@pokacyb - I think this PR is almost done, would you like to work on something else?

2021-08-15 03:54 UTC, Janhavi-2001 commented
I've made the changes as per your requirements. Feel free to check them out!

2021-08-22 06:28 UTC, Akshu-on-github commented
LGTM, thanks for contributing!

2021-08-22 06:29 UTC, Akshu-on-github approved these changes
LGTM ✅ 
Thanks for making the requested changes!

2021-08-22 06:30 UTC, merged

2021-08-30 08:10 UTC, pokacyb commented
@Akshu-on-github 
Github didn't send me a notification for your message for some reason.
Sure I'll do anything :)